import random                ## importing random module...
a=random.randint(10,50)      ## Storing the random value in a...
attempts=1                   ## initialize the attempts for storing the count of attempts...
print("Welcome!")            ## Message printing...
Name=input("Enter your name: ")         ## Message printing...

while(True):                 ## infinite loop 
    n=int(input(f"{Name} enter the number you're gusseing: "))     ## Taking an interger from user and storing it into n...
    if(a>n):                 ## Condition checking if a>n
        attempts+=1          ## incrementing attempts...
        print(f"Please enter higher number....")           ## Message printing...
    elif(a<n):               ## another ondition cheching if a<n
        attempts+=1          ## incrementing attempts...
        print(f"Please enter lower number....")        ## Message printing...
    else:                    ## last condition where a==n...
        print(f"{Name} you have gussed the number at {attempts} no attempts....")       ## Message printing...
        print(f"Actual number is {n}")                                           ## Message printing...
        break                                                   ## break the loop...
print("Thank you for playing this game...")         ## Message printing...







